import type { Job } from '../../types';
import { createId } from '../../utils/format';

/**
 * Demo seed data.
 *
 * These are clearly fictional sample records used to make the UI demonstrable
 * (a richer spread across every tracker stage so dashboards and graphs render
 * nicely). They are never presented as live job-market data.
 */

interface SeedJob {
  companyName: string;
  jobTitle: string;
  status: Job['status'];
  location: string;
  salaryRange: string;
  experience: string;
  jobType: string;
  resumeUsed: string;
  dateApplied?: string;
  linkedinUrl?: string;
  recruiterName?: string;
  recruiterEmail?: string;
  notes?: string;
  followUpDate?: string;
  interviewDate?: string;
  interviewRound?: string;
  rejectionReason?: string;
}

const DAY = 86_400_000;
const daysAgo = (n: number) => new Date(Date.now() - n * DAY).toISOString();
const daysFromNow = (n: number) => new Date(Date.now() + n * DAY).toISOString();

const SEED: SeedJob[] = [
  // ---------- Wishlist (saved, not yet applied) ----------
  {
    companyName: 'Microsoft',
    jobTitle: 'QA Automation Lead',
    status: 'wishlist',
    location: 'Hyderabad / Hybrid',
    salaryRange: '₹30–40 LPA',
    experience: 'Lead',
    jobType: 'Full-time',
    resumeUsed: 'QA_Lead_Resume_v3',
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-microsoft-qa-lead',
    recruiterName: 'Priya Sharma',
    notes: 'Strong Azure + Playwright focus. Demo record only.',
  },
  {
    companyName: 'Google',
    jobTitle: 'SDET Engineer',
    status: 'wishlist',
    location: 'Bengaluru / On-site',
    salaryRange: '₹35–45 LPA',
    experience: 'Senior Level',
    jobType: 'Full-time',
    resumeUsed: 'SDET_Resume_v4',
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-google-sdet',
    recruiterName: 'Arun Nair',
    notes: 'Demo record only. C++ and mobile testing preferred.',
  },
  {
    companyName: 'Netflix',
    jobTitle: 'Senior QA Engineer - Streaming',
    status: 'wishlist',
    location: 'Remote',
    salaryRange: '₹50–70 LPA',
    experience: 'Senior Level',
    jobType: 'Full-time',
    resumeUsed: 'QA_Lead_Resume_v3',
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-netflix-qa',
    notes: 'Demo record only. Performance and chaos testing focus.',
  },
  {
    companyName: 'Uber',
    jobTitle: 'Test Automation Engineer',
    status: 'wishlist',
    location: 'Bengaluru / Hybrid',
    salaryRange: '₹25–35 LPA',
    experience: 'Mid Level',
    jobType: 'Full-time',
    resumeUsed: 'SDET_Resume_v4',
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-uber-qa',
    notes: 'Demo record only.',
  },
  {
    companyName: 'Spotify',
    jobTitle: 'QA Engineer - Mobile',
    status: 'wishlist',
    location: 'Remote',
    salaryRange: '₹28–40 LPA',
    experience: 'Mid Level',
    jobType: 'Full-time',
    resumeUsed: 'SDET_Resume_v4',
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-spotify-mobile-qa',
    notes: 'Demo record only. Appium experience valued.',
  },
  {
    companyName: 'Stripe',
    jobTitle: 'SDET - Payments Platform',
    status: 'wishlist',
    location: 'Remote',
    salaryRange: '₹40–55 LPA',
    experience: 'Senior Level',
    jobType: 'Full-time',
    resumeUsed: 'QA_Architect_Resume_v2',
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-stripe-sdet',
    notes: 'Demo record only.',
  },

  // ---------- Applied ----------
  {
    companyName: 'Amazon',
    jobTitle: 'Test Automation Architect',
    status: 'applied',
    location: 'Chennai / Hybrid',
    salaryRange: '₹40–55 LPA',
    experience: 'Architect',
    jobType: 'Full-time',
    resumeUsed: 'QA_Architect_Resume_v2',
    dateApplied: daysAgo(3),
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-amazon-architect',
    recruiterName: 'Priya Sharma',
    recruiterEmail: 'priya.sharma@example.com',
    notes: 'Applied via LinkedIn. Demo record only.',
    followUpDate: daysFromNow(2),
  },
  {
    companyName: 'Atlassian',
    jobTitle: 'Senior QA Engineer',
    status: 'applied',
    location: 'Remote',
    salaryRange: '₹25–35 LPA',
    experience: 'Senior Level',
    jobType: 'Full-time',
    resumeUsed: 'QA_Lead_Resume_v3',
    dateApplied: daysAgo(7),
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-atlassian-senior-qa',
    recruiterName: 'David Chen',
    notes: 'Demo record only. Jira/Confluence automation experience valued.',
  },
  {
    companyName: 'Flipkart',
    jobTitle: 'SDET Lead',
    status: 'applied',
    location: 'Bengaluru / On-site',
    salaryRange: '₹30–40 LPA',
    experience: 'Lead',
    jobType: 'Full-time',
    resumeUsed: 'SDET_Resume_v4',
    dateApplied: daysAgo(2),
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-flipkart-sdet-lead',
    recruiterName: 'Meera Krishnan',
    recruiterEmail: 'meera.k@example.com',
    notes: 'Demo record only. Applied through referral.',
    followUpDate: daysFromNow(4),
  },
  {
    companyName: 'PayPal',
    jobTitle: 'QA Engineer - Payments',
    status: 'applied',
    location: 'Chennai / Hybrid',
    salaryRange: '₹22–30 LPA',
    experience: 'Mid Level',
    jobType: 'Full-time',
    resumeUsed: 'SDET_Resume_v4',
    dateApplied: daysAgo(5),
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-paypal-qa',
    recruiterName: 'Ravi Menon',
    notes: 'Demo record only.',
    followUpDate: daysFromNow(3),
  },
  {
    companyName: 'Swiggy',
    jobTitle: 'Automation QA Engineer',
    status: 'applied',
    location: 'Bengaluru / Hybrid',
    salaryRange: '₹18–26 LPA',
    experience: 'Mid Level',
    jobType: 'Full-time',
    resumeUsed: 'QA_Lead_Resume_v3',
    dateApplied: daysAgo(9),
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-swiggy-qa',
    recruiterName: 'Kavya Reddy',
    notes: 'Demo record only.',
    followUpDate: daysFromNow(1),
  },

  // ---------- Follow-up ----------
  {
    companyName: 'Adobe',
    jobTitle: 'QA Automation Engineer - API',
    status: 'follow_up',
    location: 'Noida / Hybrid',
    salaryRange: '₹20–30 LPA',
    experience: 'Mid Level',
    jobType: 'Full-time',
    resumeUsed: 'SDET_Resume_v4',
    dateApplied: daysAgo(12),
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-adobe-api-qa',
    recruiterName: 'Neha Gupta',
    recruiterEmail: 'neha.gupta@example.com',
    notes: 'Follow-up sent. Demo record only.',
    followUpDate: daysFromNow(1),
  },
  {
    companyName: 'Walmart Global Tech',
    jobTitle: 'Senior SDET (QA)',
    status: 'follow_up',
    location: 'Bengaluru / Hybrid',
    salaryRange: '₹28–38 LPA',
    experience: 'Senior Level',
    jobType: 'Full-time',
    resumeUsed: 'QA_Lead_Resume_v3',
    dateApplied: daysAgo(15),
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-walmart-sdet',
    recruiterName: 'Sandeep Kulkarni',
    recruiterEmail: 'sandeep.k@example.com',
    notes: 'Demo record only. Recruiter replied, follow-up due.',
    followUpDate: daysFromNow(1),
  },
  {
    companyName: 'Accenture',
    jobTitle: 'QA Test Lead',
    status: 'follow_up',
    location: 'Pune / Hybrid',
    salaryRange: '₹16–24 LPA',
    experience: 'Lead',
    jobType: 'Full-time',
    resumeUsed: 'QA_Lead_Resume_v3',
    dateApplied: daysAgo(18),
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-accenture-test-lead',
    recruiterName: 'Anita Desai',
    notes: 'Demo record only.',
    followUpDate: daysFromNow(2),
  },

  // ---------- Interview ----------
  {
    companyName: 'Salesforce',
    jobTitle: 'QA Architect',
    status: 'interview',
    location: 'Bengaluru / Hybrid',
    salaryRange: '₹45–60 LPA',
    experience: 'Architect',
    jobType: 'Full-time',
    resumeUsed: 'QA_Architect_Resume_v2',
    dateApplied: daysAgo(20),
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-salesforce-qa-architect',
    recruiterName: 'Rahul Verma',
    recruiterEmail: 'rahul.verma@example.com',
    notes: 'Demo record only. Round 2 completed.',
    interviewDate: daysAgo(-2),
    interviewRound: 'Round 2 - Technical',
  },
  {
    companyName: 'Oracle',
    jobTitle: 'Test Lead - Cloud',
    status: 'interview',
    location: 'Bengaluru / Hybrid',
    salaryRange: '₹32–42 LPA',
    experience: 'Lead',
    jobType: 'Full-time',
    resumeUsed: 'QA_Lead_Resume_v3',
    dateApplied: daysAgo(15),
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-oracle-cloud-test-lead',
    recruiterName: 'Sneha Reddy',
    notes: 'Demo record only. Panel round scheduled.',
    interviewDate: daysAgo(-1),
    interviewRound: 'Round 3 - Panel',
  },
  {
    companyName: 'Intuit',
    jobTitle: 'Senior QA Engineer - QuickBooks',
    status: 'interview',
    location: 'Bengaluru / Hybrid',
    salaryRange: '₹30–42 LPA',
    experience: 'Senior Level',
    jobType: 'Full-time',
    resumeUsed: 'SDET_Resume_v4',
    dateApplied: daysAgo(10),
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-intuit-qa',
    recruiterName: 'Vikram Rao',
    recruiterEmail: 'vikram.rao@example.com',
    notes: 'Demo record only. First round done, second scheduled.',
    interviewDate: daysAgo(3),
    interviewRound: 'Round 1 - Screening',
  },
  {
    companyName: 'ThoughtWorks',
    jobTitle: 'QA Consultant',
    status: 'interview',
    location: 'Bengaluru / Hybrid',
    salaryRange: '₹24–34 LPA',
    experience: 'Senior Level',
    jobType: 'Full-time',
    resumeUsed: 'QA_Lead_Resume_v3',
    dateApplied: daysAgo(12),
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-thoughtworks-qa',
    recruiterName: 'Deepa Menon',
    notes: 'Demo record only.',
    interviewDate: daysAgo(4),
    interviewRound: 'Round 1 - Pairing',
  },

  // ---------- Offer ----------
  {
    companyName: 'Zoho',
    jobTitle: 'Senior SDET',
    status: 'offer',
    location: 'Chennai / On-site',
    salaryRange: '₹24–30 LPA',
    experience: 'Senior Level',
    jobType: 'Full-time',
    resumeUsed: 'SDET_Resume_v4',
    dateApplied: daysAgo(30),
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-zoho-senior-sdet',
    recruiterName: 'Karthik Iyer',
    recruiterEmail: 'karthik.iyer@example.com',
    notes: 'Demo record only. Offer received after final round.',
    interviewDate: daysAgo(-10),
    interviewRound: 'Round 4 - Final',
  },
  {
    companyName: 'PhonePe',
    jobTitle: 'Test Automation Lead',
    status: 'offer',
    location: 'Bengaluru / On-site',
    salaryRange: '₹32–40 LPA',
    experience: 'Lead',
    jobType: 'Full-time',
    resumeUsed: 'QA_Lead_Resume_v3',
    dateApplied: daysAgo(25),
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-phonepe-test-lead',
    recruiterName: 'Nikhil Bhat',
    recruiterEmail: 'nikhil.bhat@example.com',
    notes: 'Demo record only. Offer in hand.',
    interviewDate: daysAgo(-8),
    interviewRound: 'Round 3 - Final',
  },
  {
    companyName: 'Freshworks',
    jobTitle: 'SDET Engineer',
    status: 'offer',
    location: 'Chennai / Hybrid',
    salaryRange: '₹18–26 LPA',
    experience: 'Mid Level',
    jobType: 'Full-time',
    resumeUsed: 'SDET_Resume_v4',
    dateApplied: daysAgo(22),
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-freshworks-sdet',
    recruiterName: 'Lakshmi Narayan',
    notes: 'Demo record only. Verbal offer received.',
    interviewDate: daysAgo(-6),
    interviewRound: 'Round 2 - Technical',
  },

  // ---------- Rejected ----------
  {
    companyName: 'Infosys',
    jobTitle: 'Test Automation Lead',
    status: 'rejected',
    location: 'Pune / Hybrid',
    salaryRange: '₹18–24 LPA',
    experience: 'Lead',
    jobType: 'Full-time',
    resumeUsed: 'QA_Lead_Resume_v3',
    dateApplied: daysAgo(25),
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-infosys-test-lead',
    recruiterName: 'Anita Desai',
    notes: 'Demo record only. Position was filled internally.',
    rejectionReason: 'Position filled internally',
  },
  {
    companyName: 'IBM',
    jobTitle: 'QA Engineer - AI Products',
    status: 'rejected',
    location: 'Remote',
    salaryRange: '₹22–30 LPA',
    experience: 'Mid Level',
    jobType: 'Full-time',
    resumeUsed: 'SDET_Resume_v4',
    dateApplied: daysAgo(40),
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-ibm-qa-ai',
    notes: 'Demo record only.',
    rejectionReason: 'Selected candidate had more AI experience',
  },
  {
    companyName: 'Cisco',
    jobTitle: 'Test Engineer - Networking',
    status: 'rejected',
    location: 'Bengaluru / Hybrid',
    salaryRange: '₹20–28 LPA',
    experience: 'Mid Level',
    jobType: 'Full-time',
    resumeUsed: 'QA_Lead_Resume_v3',
    dateApplied: daysAgo(35),
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-cisco-qa',
    recruiterName: 'Rohit Sharma',
    notes: 'Demo record only. Rejected after first round.',
    rejectionReason: 'Stronger candidates in pipeline',
  },
  {
    companyName: 'Deloitte',
    jobTitle: 'QA Automation Consultant',
    status: 'rejected',
    location: 'Hyderabad / Hybrid',
    salaryRange: '₹15–22 LPA',
    experience: 'Mid Level',
    jobType: 'Contract',
    resumeUsed: 'SDET_Resume_v4',
    dateApplied: daysAgo(28),
    linkedinUrl: 'https://www.linkedin.com/jobs/view/example-deloitte-qa',
    recruiterName: 'Shalini Gupta',
    notes: 'Demo record only.',
    rejectionReason: 'Budget approved for lower band',
  },
];

export function buildSeedJobs(): Job[] {
  const now = Date.now();
  return SEED.map((seed, index) => {
    const createdAt = daysAgo(60 - index * 2);
    const id = createId('job');
    return {
      id,
      companyName: seed.companyName,
      jobTitle: seed.jobTitle,
      status: seed.status,
      location: seed.location,
      salaryRange: seed.salaryRange,
      experience: seed.experience,
      jobType: seed.jobType,
      resumeUsed: seed.resumeUsed,
      dateApplied: seed.dateApplied,
      linkedinUrl: seed.linkedinUrl,
      recruiterName: seed.recruiterName,
      recruiterEmail: seed.recruiterEmail,
      notes: seed.notes,
      followUpDate: seed.followUpDate,
      interviewDate: seed.interviewDate,
      interviewRound: seed.interviewRound,
      rejectionReason: seed.rejectionReason,
      createdAt,
      updatedAt: new Date(now - index * DAY).toISOString(),
    };
  });
}
